name: 'edge-computing-deploy'
description: 'This action was created to help deploy an edge application at Azion.'
inputs:
  applicationName:
    description: 'Application Name'
    required: true
  azionPersonalToken:
    description: 'Azion Personal Token'
    required: true
  commitConfig:
    description: 'Commit config azion'
    required: false
    default: true
  functionFilePath:
    description: 'Path function file ex: worker/function.js'
    required: false
    default: 'worker/function.js'
  functionArgsFilePath:
    description: 'Path function args file ex: args.json' # no commit this file
    required: false
    default: 'args.json'
  configFilePath:
    description: 'Path config file ex: azion/azion.json'
    required: false
    default: 'azion/azion.json'

outputs:
  applicationId:
    description: 'Return application id'  
runs:
  using: 'node16'
  main: 'index.js'

branding:
  icon: cloud-lightning
  color: orange