name: 'edge-computing-deploy'
description: 'This action was created to help deploy an edge application at Azion.'
inputs:
  applicationName:
    description: 'Application Name'
    required: false
  azionPersonalToken:
    description: 'Azion Personal Token'
    required: true
  functionArgsFilePath:
    description: 'Path function args file ex: args.json' # no commit this file
    required: false
    default: 'args.json'
  buildPreset:
    description: 'build Preset'
    required: true
  buildMode:
    description: 'build Mode'
    required: false
    default: 'deliver'


outputs:
  applicationId:
    description: 'Return application id'

runs:
  using: 'docker'
  image: 'docker://josebsf/edge-computing-deploy:latest'
  

branding:
  icon: cloud-lightning
  color: orange